repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-unit-tests
        args: [
          "./api/user -v"
        ]
