version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGES_USER: ${DB_USER}
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql